**Numpy Array**


1.   Declare Array
2.   2Dimesional Array (shape)
3.   Lenght of the array/Shape af the array/Dimension of the array/Size of the array/ItemSize/Bytes
4.   Operations on arrays
5.   Deleting array
6.   Delete array
7.   Print and specify the data type
8.   random.random
9.   random.randint
10.  linspace
11.  arange
12.  Eye
13.  Empty
14.  Reshape
15.  Concatenate
16.  Stack (Vertical stack and Horizontal Stack)
17.  Splitting arrays(vertical split and horizontal split)
18.  Copy

In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(a.shape)
print(type(a))

b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(b)
print(b.shape)

c = np.array([1,'a'])
print(c)
print(type(c))

d = np.array([5,10,15])
e=d/5.0
print(e)

del d

a = np.array([[1],[2]])
b = np.copy(a)

print(a.shape)
print(b.shape)

[1 2 3]
(3,)
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
['1' 'a']
<class 'numpy.ndarray'>
[1. 2. 3.]
(2, 1)
(2, 1)


In [26]:
b = np.array([1,2,3])
print(len(b))
print(b.ndim)
print(b.size)
print(b.itemsize)
print(b.nbytes)

3
1
3
8
24


In [3]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(b[2][-1])  #Using -1 to print the last element

9


In [3]:
a = np.array([1,2,3,4],dtype='float32')
print(a)
print(type(a))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [12]:
import numpy as np
a =  np.random.random((3,3))
print(a)

[[0.20273633 0.27562417 0.28227577]
 [0.32141524 0.09102494 0.64711807]
 [0.51230544 0.31546181 0.98913991]]


In [17]:
import numpy as np
a =  np.random.randint(0,20,(3,3))
print(a)

[[ 2  0  0]
 [10  6 16]
 [ 9 17  3]]


In [19]:
import numpy as np
a =  np.linspace(0,10,3)
print(a)

[ 0.  5. 10.]


In [22]:
import numpy as np
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
import numpy as np
a = np.empty(5)
a

array([1., 1., 1., 1., 1.])

In [6]:
import numpy as np
a = np.zeros((2,3))
print(a)
print(type(a))

b = np.ones((2,3))
print(b)
print(type(b))

c = np.array([[0,0,0],[0,0,0]],dtype='float32')
print(c)
print(type(c))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [18]:
a = np.random.random((3,3))
print(len(a))
print(a.ndim)
print(a.size)

3
2
9


#### Array Slicing 

In [46]:
a =np.arange(10)
print(a)
print(a[:])
print(a[:3])
print(a[3:])
print(a[2:9])
print(a[2:9])
print(a[::2])
print(a[1::2])
print(a[::])
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]
[2 3 4 5 6 7 8]
[0 2 4 6 8]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [55]:
a = np.arange(10)
print(a)
b = np.array([1,2,3,4,5])
print(b)
c = np.random.random(10)
print(c)
c = np.random.randint(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[0.98306513 0.23995066 0.92686083 0.55614642 0.23983756 0.62984117
 0.56929275 0.71161006 0.56242294 0.2333193 ]
4


**Operations on array matrix**


1.   Slicing into the array (n dimesional arrays
2.   Reverse the arrays
3.   Print First column
3.   Print First row
4.   Altering the array element

In [77]:
a = np.array([[1,2,3,6],
             [4,5,6,4],
             [7,8,9,0]])
print(a[:2,:3])
print(a[:2,:2])
print(a[:3,:2])
print(a[:,0])
print(a[0,:])
print(a[::-1,::-1])

sub_array = a[:2,:2]
print(sub_array)
sub_array[0,0]=12
print(sub_array)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]
 [7 8]]
[1 4 7]
[1 2 3 6]
[[0 9 8 7]
 [4 6 5 4]
 [6 3 2 1]]
[[1 2]
 [4 5]]
[[12  2]
 [ 4  5]]


#### Reshape
1. Using Axis
2. Cocatenate

In [1]:
import numpy as np
a = np.array([[1,2],
             [4,5],
             [7,8]])
print(a)
print("Before",a.shape)

b=a.reshape(2,3)
print("After",b.shape)
print(b)

[[1 2]
 [4 5]
 [7 8]]
Before (3, 2)
After (2, 3)
[[1 2 4]
 [5 7 8]]


In [11]:
x = np.array([1,2,3])
print(x)
print(x.shape)
y = x.reshape(3,1)
print(y)
print(y.shape)

[1 2 3]
(3,)
[[1]
 [2]
 [3]]
(3, 1)


In [13]:
x = np.array([1,2,3])
x.reshape((3,1))

array([[1],
       [2],
       [3]])

#### Usage of Axis to do reshaping

In [17]:
x = np.array([1,2,3])
print(x[:,np.newaxis])
print(x[np.newaxis,:])

[[1]
 [2]
 [3]]
[[1 2 3]]


#### Concatenate 

In [20]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = np.concatenate([a,b])
print(c)

c1 = a+b
print(c1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 7  9 11 13 15]


In [2]:
import numpy as np
a = np.array([[1,2,3,4],
             [5,6,7,8]])
b = np.concatenate([a,a])
print(b)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


#### Stacking
- Vertical stack
- Horizontal stack

In [3]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([7,8,9])

c = np.vstack([a,b])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[7,8,9],
            [10,11,12]])

c = np.hstack([a,b])
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#### Splitting of arrays

In [11]:
x = np.arange(8.0)
print(x)
np.split(x, [3, 5, 6, 10])

[0. 1. 2. 3. 4. 5. 6. 7.]


[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [16]:
x = [1,2,3,4,5,6,7,8]
x1,x2,x3 = np.split(x,[4,4])
print(x1)
print(x2)
print(x3)

[1 2 3 4]
[]
[5 6 7 8]


In [1]:
import numpy as np
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
upper,lower = np.vsplit(a,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [4]:
left,right = np.hsplit(a,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#### Computation on Numpy Arrays : Universal Function

In [3]:
import numpy as np
def reciprocal(a):
    for i in a:
        return 1/i
    
b = b=[1,2,3]
reciprocal(b)

1.0

In [11]:
a = np.arange(10)
print(a)
b = np.random.randint(8,10)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[8 9 9 9 8]


In [18]:
a = np.empty([2,3])
print(a)

[[7.26515746e-315 7.26515762e-315 7.26437083e-315]
 [0.00000000e+000 1.21968716e-311 1.21963496e-311]]
